### ISSUE TITLE
Add Native Scrollbar to Mercury-Win7

### ISSUE THREAD

**Issue by MasterSlenderTR** [Alex313031/Mercury-Win7#1]
Please integrate this patch https://github.com/ephemeralViolette/firefox-native-controls into Mercury-Win7, I hate seeing Mozilla's forced Win10 scrollbar in my Win7. This was also requested for regular Mercury https://github.com/Alex313031/Mercury/issues/62 but I assume Alex did not see it.

Lack of native scrollbar patch in Mercury is the only reason that still makes me use stock Firefox 115 ESR instead of Mercury.
![Capture](https://github.com/Alex313031/Mercury-Win7/assets/50411937/00d829ec-32dd-494e-a1a9-cd3d907505e3)

**Comment by Alex313031** [comment]
@MasterSlenderTR Will definitely add this! This is great, its one of my complaints of firefox on win7

**Comment by Alex313031** [comment]
@MasterSlenderTR Wait, how does vanilla Firefox ESR have this? Did you or someone else compile it with that patch added?

**Comment by MasterSlenderTR** [comment]
> @MasterSlenderTR Wait, how does vanilla Firefox ESR have this? Did you or someone else compile it with that patch added?

I just used the binary patch that repo had.

**Comment by MasterSlenderTR** [comment]
> @MasterSlenderTR Will definitely add this! This is great, its one of my complaints of firefox on win7
> 
> UPDATE: Added

UPDATE 2: It's gone in 121 version of thorium-win7

**Comment by Alex313031** [comment]
@MasterSlenderTR The 121 is a beta, and doesn't have this patch.

Next release will still be based on ESR 115, and will have the patch included as well as enabled by default (no longer have to set a setting in about:config)

**Comment by MasterSlenderTR** [comment]
Fyi there's a new release of native scrollbar patch that revives more native controls such as tooltip and statusbar https://github.com/ephemeralViolette/firefox-native-controls/releases/tag/esr-115.7.0-native-controls-patch you should integrate the new changes.

**Comment by Alex313031** [comment]
@MasterSlenderTR This is literally the exact patch I was already using. I'm about to make Mercury Win7 v122.0.2, this will be a stable release. It will fix the subsystem version thing I mentioned in the release notes for 121, and will have this scrollbar patch.

**Comment by K4sum1** [comment]
@Alex313031 122 requires a lot more, a lot more. Just applying the 115.7 scrollbar patch will not work. Message me on Discord for more info.

**Comment by Alex313031** [comment]
@MasterSlenderTR @K4sum1 Damn, I didn't know that. OK I will hop on there. Also, I'm gonna make a few minor commits to the repo today. As you can see, I already merged two minor patches from upstream. If I ever make a commit that you don't want, let me know.
