### ISSUE TITLE
Release version based on Firefox ESR 115.6.0

### ISSUE THREAD

**Issue by zooool** [Alex313031/Mercury-Win7#2]
See title.

**Comment by Alex313031** [comment]
@zooool Yup, working on it.

**Comment by zooool** [comment]
> @zooool Yup, working on it.

Awesome. Will you also build AVX2 builds?

**Comment by Alex313031** [comment]
@zooool No, no AVX2 builds, sorry. Too much building for all my projects and all the platforms and SSE3, SSE4, AVX, AVX2, etc. My computer is almost always loaded lol and it gets frustrating.

**Comment by Alex313031** [comment]
@zooool I will not be providing AVX2 builds.
