### ISSUE TITLE
Compile AVX2 builds if possible

### ISSUE THREAD

**Issue by MasterSlenderTR** [Alex313031/Mercury-Win7#4]
My Ryzen 5 5500 supports AVX2 so I'd prefer having AVX2 version of Mercury-win7 instead of AVX.

Note: Thanks for making Mercury-Win7, enjoying it so far with customizations I did.
![Untitled](https://github.com/Alex313031/Mercury-Win7/assets/50411937/d4822bce-15c1-4910-9e39-4b1a8d51489d)

**Comment by Alex313031** [comment]
@MasterSlenderTR You were the guy that made the post in r/Windows7 where the guy asked about the wallpaper being from Vista RTM setup arent you lol.

Nice custom desktop icons, and nice custom user.js and css. Can you share, I might tweak it and use it for my own Mercury setup.

I can make an AVX2 build. However, you should turn off any AVX offsets, if applicable. Because if not, the clock speed decrease will trump any performance increase.

**Comment by zooool** [comment]
Alex promised that he **would NOT** compile AVX2 builds: https://github.com/Alex313031/Mercury-Win7/issues/2#issuecomment-1893162416

**Comment by MasterSlenderTR** [comment]
> @MasterSlenderTR You were the guy that made the post in r/Windows7 where the guy asked about the wallpaper being from Vista RTM setup arent you lol, I recognize your desktop from that post.
> 
> Nice custom desktop icons, and nice custom user.js and css. Can you share, I might tweak it and use it for my own Mercury setup.
> 
> I can make an AVX2 build. However, you should turn off any AVX offsets, if applicable. Because if not, the clock speed decrease will trump any performance increase.
> 
> Also, I am sadly banned from that reddit, because I made a post about Thorium-Win7 and they categorized it as advertising. I tried to contact them and explain, and apologize and not do it again, but now I'm frustrated because I often want to comment on stuff especially when people need help and I know how to fix it. Oh well. Maybe in the future I'll make a burner account, but I hate doing that and its annoying to have to log in and out of stuff.

Yes, I was that guy. Here's link to the theme I used in screenshot: https://forum.eclectic4un.me/viewtopic.php?f=43&t=48 and I'd like to use an AVX2 build if you make one but you should tell me how do I turn off AVX offsets.

**Comment by K4sum1** [comment]
I think Ryzen is unaffected by AVX offsets. I've only ever heard about that on Intel chips.

Also if you can make a 10 VM, build with this mozconfig, and you have AVX2 build.
https://github.com/Alex313031/Mercury-Win7/blob/main/mozconfigs/mozconfig-win-avx2

**Comment by jonm58** [comment]
> I think Ryzen is unaffected by AVX offsets. I've only ever heard about that on Intel chips.
> 
> Also if you can make a 10 VM, build with this mozconfig, and you have AVX2 build. https://github.com/Alex313031/Mercury-Win7/blob/main/mozconfigs/mozconfig-win-avx2

AMD Zen3 Ryzen process support AVX512

**Comment by zooool** [comment]
Not sure why [my comment](https://github.com/Alex313031/Mercury-Win7/issues/4#issuecomment-1910487342) is being ignored but this issue should be CLOSED as I already asked this question and Alex said he **WOULD NOT** compile AVX2 builds.

**Comment by K4sum1** [comment]
> Not sure why [my comment](https://github.com/Alex313031/Mercury-Win7/issues/4#issuecomment-1910487342) is being ignored but this issue should be CLOSED as I already asked this question and Alex said he **WOULD NOT** compile AVX2 builds.

What part of "I can make an AVX2 build" is would not?

**Comment by zooool** [comment]
> > Not sure why [my comment](https://github.com/Alex313031/Mercury-Win7/issues/4#issuecomment-1910487342) is being ignored but this issue should be CLOSED as I already asked this question and Alex said he **WOULD NOT** compile AVX2 builds.
> 
> What part of "I can make an AVX2 build" is would not?

He already said **no**.

**Comment by jonm58** [comment]
> > > Not sure why [my comment](https://github.com/Alex313031/Mercury-Win7/issues/4#issuecomment-1910487342) is being ignored but this issue should be CLOSED as I already asked this question and Alex said he **WOULD NOT** compile AVX2 builds.
> > 
> > 
> > What part of "I can make an AVX2 build" is would not?
> 
> He already said **no**。

https://github.com/Alex313031/Mercury-Win7/issues/2#issuecomment-1893162416
I mean this?

**Comment by K4sum1** [comment]
> [#2 (comment)](https://github.com/Alex313031/Mercury-Win7/issues/2#issuecomment-1893162416) your mean this?

Ok, but that comment came before the later comment [here](https://github.com/Alex313031/Mercury-Win7/issues/4#issuecomment-1902600139) where he says he can.

**Comment by K4sum1** [comment]
@Alex313031 What's your new system?

**Comment by K4sum1** [comment]
> @K4sum1 Ryzen 3800XT overclocked to 4.4Ghz all cores, 32GB 3200Mhz DDR4.

Interesting build, guessing you found a good used deal?

Overclocking RAM would probably help a fair bit, try for 3600 or 3800. However you'll want to make sure it's 100% stable for building.

**Comment by MasterSlenderTR** [comment]
Is there ETA for the new release of Mercury-Win7?

**Comment by Alex313031** [comment]
@K4sum1 Well, this computer is a frankenstein build, with parts added and removed individually over the years. Some parts were free, some were used, some new. I can't tell you exactly how it all came to be. And yeah I know, but this system will not run any higher than 3200Mhz. no matter what I do. I have tried voltages, timings, BIOS revisions, CPU mem controller frequencies, stepping down my overclock. Trying stock settings, and only changing the ram speed. Nothing works, and I'm fine with it. Still plenty fast.

@MasterSlenderTR New builds based on ESR 115.9.0 are building as we speak. They will be released tonight/tommorow morning.

**Comment by Alex313031** [comment]
@MasterSlenderTR Here y'all go > https://github.com/Alex313031/Mercury-Win7/releases/tag/v.115.9.0
