### ISSUE TITLE
Variable font is not supported on Win7

### ISSUE THREAD

**Issue by brynne8** [Alex313031/Mercury-Win7#5]
Test site: https://stricjs.netlify.app/docs/intro.html

The site uses a variable font "Inter" and if it's not supported, the headings would all appear in same font weight.

**Comment by Alex313031** [comment]
@brynne8 Interesting, I can confirm it occurs.

**Comment by brynne8** [comment]
I'm using beta 121

**Comment by brynne8** [comment]
@K4sum1 Is this issue related to your vyvfox?

**Comment by K4sum1** [comment]
I see no difference between Waterfox G6 and Mercury 121. I have no idea what I'm even supposed to be looking for.
