### ISSUE TITLE
Older CPU (non-AVX) Support in the Future?

### ISSUE THREAD

**Issue by Uka-Uka** [Alex313031/Mercury-Win7#7]

**Comment by K4sum1** [comment]
I'm assuming that's coming, but Mercury-Win7 is pretty much this with a few extra tweaks. Same SSE3 support as regular Firefox.

https://github.com/Eclipse-Community/r3dfox

**Comment by Uka-Uka** [comment]
@K4sum1 Thanks for pointing that out and for your awesome work on r3dfox. are you and @Alex313031 planning to unify the two projects eventually? or do r3dfox and Mercury serve different purposes?

**Comment by K4sum1** [comment]
> @K4sum1 Thanks for pointing that out and for your awesome work on r3dfox. are you and @Alex313031 planning to unify the two projects eventually? or do r3dfox and Mercury serve different purposes?

Maybe at some point idk.

**Comment by Alex313031** [comment]
@Uka-Uka Mercury serves the purpose of being stable and having compiler optimizations, and removing annoying stuff like telemetry and Pocket, etc. r3dfox serves the purpose of bringing the latest features and bug fixes to Windows 7/8/8.1 They are both about equal as far as security is concerned, and will continue to be until October of this year when ESR 115 becomes EOL.

We might merge after that point. For now though, I am just helping a little bit with r3dfox. I will occasionally push out a beta build of Mercury for Windows 7 based on newer Firefox, but the stable releases will continue to be based on ESR 115 until October.

I will be making SSE3, SSE4, AVX, and AVX2 builds this release (which are going to be released tommorow, I am building them all right now). This way it will cover all the bases: no matter what hardware you have, as long as you have a 64 bit CPU, you will be able to run one of the releases.

**Comment by K4sum1** [comment]
> We might merge after that point. For now though, I am just helping a little bit with r3dfox.

We really need better communication for that. I've been trying to get you to hop on Discord so I can discuss some stuff with you.

**Comment by adeii** [comment]
Good news: mercury_122.0.2_win64_SSE3 also could be run on Win7.

Just install VxKex 1.1 and add API-MS-WIN-SHCORE-SCALING-L1-1-1.dll to mercury folder.
And use modded .exe (in CFF Explorer) that can run on Win 7.  https://ufile.io/sevgn92g

**Comment by ioc2e3** [comment]
Have always misunderstood ...

Thought that CPUs without ( AVX )( AVX2 )( SSE3 )( SSE4 ) ...

were relatively new ...

.
