### ISSUE TITLE
Addons not loading after moving program to different drive letter

### ISSUE THREAD

**Issue by narinishi** [Alex313031/Mercury-Win7#8]
Version: 121.0.1 (64-bit)

After moving Mercury's entire folder to a different drive letter, my addons are no longer loading. When I go to about:addons, all of them are still listed as enabled but some of their icons are missing. When I click the addons button in the toolbar, only one of the addons shows.

**Comment by K4sum1** [comment]
This is a weird upstream issue. You have the enable and disable them a few times until the icons reappear, then they should work again.

**Comment by narinishi** [comment]
Thank you for the help
